name: CI raspberry

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
        go: [1.17]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:        
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build on ${{ matrix.os }} and Go ${{ matrix.go }}
        run: make build


      
