name: CI raspberry

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:        
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rlaskowski/easymotion:latest

      - name: Stop Container
        run: docker compose down

      - name: Run Container
        run: docker compose up


      
