name: CI raspberry

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-raspi:
    strategy:
      matrix:
        os: [self-hosted]
        go: [1.17.x]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Easymotion bin exists
        id: easymotion_exists
        run: andstor/file-existence-action@v1
        with:
          files: "dist/easymotion"
      - name: Stop Easymotion
        if: "steps.easymotion_exists.outputs.files_exists = 'true'"
        run: dist/easymotion uninstall
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make build-raspi

      - name: Install Service
        run: sudo dist/easymotion install


      
