name: easymotion
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
        go: [1.17.x]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:        
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      
      - name: Set GOROOT
        run: |
          cp -f `which go` /usr/bin/go

      - name: Build on Go ${{ matrix.go }}
        run: make build


      
