# This is a basic workflow to help you get started with Actions

name: CI Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-raspi:
    strategy:
      matrix:
        os: [self-hosted]
        go: [1.17]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make build-raspi

      - name: Uninstall Service
        run: sudo dist/easymotion uninstall

      - name: Install Service
        run: sudo dist/easymotion install

      - name: Start Service
        run: sudo systemctl start EasyMotion

      
